RULE_45 = {
    "Committee on Aviation": {
        "2023-10-30": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/Rule%2045%20Report_October%202023_Aviation_10312023.pdf?VersionId=rlMVTSB2EOVOlU0gLSiDiXSGvPu36nAs",
            "attendance": [
                "O'Shea",
                "Curtis",
                "Hopkins",
                "Robinson",
                "Dowell",
                "Harris",
                "Lee",
                "Quinn",
                "Rodriquez",
                "Tabares",
                "Ervin",
                "Cardona",
                "Sposato",
                "Nugent",
                "Napolitano",
            ],
        },
    },
    "Committee on Environmental Protection and Energy": {
        "2023-11-06": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/Environmental%20November%20Rule%2045.pdf?VersionId=KpVxhoT3yntrgcItUdg202jYB.AelUNe",
            "attendance": [
                "Hadden",
                "Knudsen",
                "La Spata",
                "Ramirez",
                "Lopez",
                "Tabares",
                "Scott, Monique L.",
                "Sigcho-Lopez",
                "Conway",
                "Lawson",
                "Martin",
                "Manaa-Hoppenworth",
                "Cruz",
            ],
        },
        "2023-09-06": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/Environmental%20September%20Rule%2045.pdf?VersionId=VJduMKrNe_TPdmRZePde1BuzivG4r_FK",
            "attendance": [
                "Hadden",
                "Knudsen",
                "La Spata",
                "Ramirez",
                "Lopez",
                "Scott, Monique L.",
                "Sigcho-Lopez",
                "Cruz",
                "Rodriguez Sanchez",
                "Conway",
                "Lawson",
                "Clay",
                "Martin",
                "Manaa-Hoppenworth",
            ],
        },
        "2023-07-12": {
            "source": None,
            "attendance": [
                "Hadden",
                "Knudsen",
                "La Spata",
                "Ramirez",
                "Lopez",
                "Tabares",
                "Scott, Monique L.",
                "Sigcho-Lopez",
                "Cruz",
                "Conway",
                "Reilly",
                "Lawson",
                "Clay",
                "Martin",
                "Manaa-Hoppenworth",
            ],
        },
    },
    "Committee on Special Events, Cultural Affairs and Recreation": {
        "2023-06-15": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/June2023MonthlyRule45.pdf?VersionId=whrd22bOZVscSDRAmtGvgu.OLy2tYF5d",
            "attendance": [
                "Sposato",
                "Scott, Monique L.",
                "Hopkins",
                "Robinson",
                "Hall",
                "Coleman",
                "Mosley",
                "Rodriguez",
                "Cruz",
                "Waguespack",
                "Nugent",
                "Napolitano",
                "Lawson",
                "Gardiner",
                "Silverstein",
            ],
        }
    },
    "Committee on Finance": {
        "2023-09-11": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/September%202023%20Rule%2045%20Report%20102323.pdf?VersionId=eJXAGbD_8Jpt_dT3fOvepjOMTIyqy7d9",
            "attendance": [
                "Dowell",
                "Conway",
                "La Spata",
                "Hopkins",
                "Hall",
                "Mitchell",
                "Harris",
                "Ramirez",
                "Quinn",
                "Lopez",
                "Moore, David H.",
                "Curtis",
                "O'Shea",
                "Mosley",
                "Rodriguez",
                "Scott, Monique L.",
                "Sigcho-Lopez",
                "Burnett",
                "Ervin",
                "Taliaferro",
                "Waguespack",
                "Rodriguez Sanchez",
                "Mitts",
                "Sposato",
                "Vasquez",
                "Knudsen",
                "Martin",
                "Silverstein",
            ],
        },
        "2023-08-29": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/August%202023%20Rule%2045%20Report%20090823.pdf?VersionId=tr11BX9ThNgpmzZ3ivwsIkNsJJqrcWnG",
            "attendance": [
                "Dowell",
                "Conway",
                "La Spata",
                "Hopkins",
                "Hall",
                "Harris",
                "Ramirez",
                "Lopez",
                "Moore, David H.",
                "Curtis",
                "Taylor",
                "Mosley",
                "Rodriguez",
                "Sigcho-Lopez",
                "Ervin",
                "Taliaferro",
                "Cardona",
                "Waguespack",
                "Rodriguez Sanchez",
                "Villegas",
                "Vasquez",
                "Reilly",
                "Knudsen",
                "Martin",
                "Silverstein",
            ],
        },
        "2023-07-17": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/July%202023%20Rule%2045%20Report%20090823.pdf?VersionId=QXwIpTHG4HanqDiK4je3k_8uQ.Ji87x4",
            "attendance": [
                "Dowell",
                "Conway",
                "La Spata",
                "Hopkins",
                "Hall",
                "Mitchell",
                "Harris",
                "Lee",
                "Quinn",
                "Lopez",
                "Moore, David H.",
                "Curtis",
                "O'Shea",
                "Taylor",
                "Mosley",
                "Rodriguez",
                "Sigcho-Lopez",
                "Burnett",
                "Ervin",
                "Taliaferro",
                "Cardona",
                "Rodriguez Sanchez",
                "Ramirez-Rosa",
                "Villegas",
                "Sposato",
                "Vasquez",
                "Reilly",
                "Knudsen",
                "Martin",
                "Silverstein",
            ],
        },
        "2023-06-14": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/June%202023%20Rule%2045%20Report%20071423.pdf?VersionId=PE0ro2jSqwgZ8Akl5DvvRTmlilgQY3Vp",
            "attendance": [
                "Dowell",
                "Conway",
                "La Spata",
                "Hopkins",
                "Hall",
                "Mitchell",
                "Harris",
                "Lee",
                "Ramirez",
                "Quinn",
                "Moore, David H.",
                "Taylor",
                "Mosley",
                "Rodriguez",
                "Scott",
                "Sigcho-Lopez",
                "Burnett",
                "Taliaferro",
                "Cardona",
                "Waguespack",
                "Ramirez-Rosa",
                "Villegas",
                "Sposato",
                "Vasquez",
                "Knudsen",
                "Martin",
                "Silverstein",
            ],
        },
    },
    "Committee on Transportation and Public Way": {
        "2023-11-09": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/Transportation%20Committee%20Rule%2045%20-%2011-23.pdf?VersionId=8ahmQy_vgGru4Cqi2EdpAvvO975t.yLM",
            "attendance": [
                "Mitchell",
                "Vasquez",
                "Ervin",
                "Fuentes",
                "Harris",
                "Moore, David H.",
                "Mosley",
                "Nugent",
                "Rodriguez",
                "Yancy",
            ],
        },
        "2023-10-03": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/Transportation%20Committee%20Rule%2045%20-%2010-23.pdf?VersionId=3u7aiZny8LVtE3Eh7AIVRW82hCRKn7DZ",
            "attendance": [
                "Mitchell",
                "Vasquez",
                "Conway",
                "Ervin",
                "Gutierrez",
                "Harris",
                "Hopkins",
                "Moore, David H.",
                "Mosley",
                "Nugent",
                "Rodriguez",
                "Waguespack",
                "Yancy",
            ],
        },
        "2023-07-13": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/Transportation%20Committee%20Rule%2045%20-%2007-23.pdf?VersionId=TvJr56KKN2ax_5fCFxJEq_Az8ac.ifQg",
            "attendance": [
                "Mitchell",
                "Vasquez",
                "Conway",
                "Fuentes",
                "Hopkins",
                "Ervin",
                "Moore, David H.",
                "Mosley",
                "Nugent",
                "Rodriguez",
                "Waguespack",
                "Yancy",
            ],
        },
        "2023-09-07": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/Transportation%20Committee%20Rule%2045%20-%2009-23.pdf?VersionId=MRscyV2LLp2t76JhwCE7iu8zgC3PSRbt",
            "attendance": [
                "Mitchell",
                "Vasquez",
                "Gutierrez",
                "Harris",
                "Hopkins",
                "Moore, David H.",
                "Mosley",
                "Nugent",
                "Rodriguez",
                "Waguespack",
                "Yancy",
            ],
        },
        "2023-06-13": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/DOC062123-06212023140325.pdf?VersionId=I.cbTXj.uuZmp6awTdrv3A8JpQ8BaX6O",
            "attendance": [
                "Mitchell",
                "Vasquez",
                "Conway",
                "Fuentes",
                "Gutierrez",
                "Harris",
                "Hopkins",
                "Moore, David H.",
                "Mosley",
                "Nugent",
                "Rodriguez",
                "Waguespack",
                "Yancy",
            ],
        },
    },
    "Committee on Pedestrian and Traffic Safety": {
        "2023-10-05": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/Pedestrian%20and%20Traffic%20Safety%20Rule%2045%20-%2010-23.pdf?VersionId=haM7hiXoi6nlZzbAPN7hg0..kIV3jqMe",
            "attendance": [
                "La Spata",
                "Cruz",
                "Robinson",
                "Yancy",
                "Chico",
                "Moore, David H.",
                "Ervin",
                "Lawson",
                "Martin",
                "Manaa-Hoppenworth",
            ],
        },
        "2023-09-06": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/Pedestrian%20and%20Traffic%20Safety%20Rule%2045%20-%2009-23.pdf?VersionId=1zPLa_OeECI.VCzd79xQ2kVI4m21fD8v",
            "attendance": [
                "La Spata",
                "Cruz",
                "Hopkins",
                "Yancy",
                "Chico",
                "Quinn",
                "Moore, David H.",
                "Burnett",
                "Knudsen",
                "Lawson",
                "Martin",
                "Manaa-Hoppenworth",
            ],
        },
        "2023-07-14": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/Pedestrian%20and%20Traffic%20Safety%20Rule%2045%20-%2007-23.pdf?VersionId=MlwIgPbHRfGGQ8JPtBKzVPnDUhbRk.2b",
            "attendance": [
                "La Spata",
                "Cruz",
                "Hopkins",
                "Robinson",
                "Yancy",
                "Chico",
                "Quinn",
                "Moore, David H.",
                "Curtis",
                "Ervin",
                "Knudsen",
                "Lawson",
                "Martin",
                "Manaa-Hoppenworth",
            ],
        },
        "2023-06-14": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/CP%26TS%20June%20Rule%2045.pdf?VersionId=NRLBXtz5Ikbst8qeAczgitMcD1iGtelY",
            "attendance": [
                "La Spata",
                "Cruz",
                "Hopkins",
                "Robinson",
                "Yancy",
                "Chico",
                "Quinn",
                "Moore, David H.",
                "Curtis",
                "Burnett",
                "Knudsen",
                "Lawson",
                "Martin",
                "Manaa-Hoppenworth",
            ],
        },
    },
    "Committee on Police and Fire": {
        "2023-09-22": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/Rule45ReportSeptember2023.pdf?VersionId=YvsjUr3d1zFebAuTNS09nDKnNFmaG3Gj",
            "attendance": [
                "Hall",
                "Mitchell",
                "Lee",
                "Curtis",
                "Taylor",
                "Mosley",
                "Tabares",
                "Ervin",
                "Cardona",
                "Sposato",
                "Nugent",
                "Knudsen",
                "Gardiner",
                "Taliaferro",
                "Robinson",
                "Clay",
                "Silverstein",
            ],
        },
    },
    "Committee on Economic, Capital and Technology Development": {
        "2023-10-02": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/ECTD%20Rule%2045%20Report%20October%202023.pdf?VersionId=8neVHsY1F0FcWKO_7VwAqKRy_E6KfhKL",
            "attendance": [
                "Villegas",
                "Mosley",
                "Hall",
                "Mitchell",
                "Chico",
                "Lee",
                "Gutierrez",
                "Tabares",
                "Cruz",
                "Cardona",
                "Waguespack",
                "Mitts",
                "Napolitano",
                "Manaa-Hoppenworth",
            ],
        },
        "2023-09-12": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/ECTD%20Rule%2045%20Report%20September%202023.pdf?VersionId=KNuWWFC80GpHzqatO0urx8_MTiIk_BtB",
            "attendance": [
                "Villegas",
                "Mosley",
                "La Spata",
                "Hall",
                "Mitchell",
                "Chico",
                "Lee",
                "Lopez",
                "Cruz",
                "Cardona",
                "Mitts",
                "Napolitano",
            ],
        },
        "2023-09-05": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/ECTD%20Rule%2045%20Report%20September%202023.pdf?VersionId=KNuWWFC80GpHzqatO0urx8_MTiIk_BtB",
            "attendance": [
                "Villegas",
                "Mosley",
                "La Spata",
                "Hall",
                "Mitchell",
                "Chico",
                "Gutierrez",
                "Tabares",
                "Cruz",
                "Cardona",
                "Waguespack",
                "Napolitano",
                "Manaa-Hoppenworth",
            ],
        },
        "2023-07-10": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/ECTD%20Rule%2045%20Report%20July%202023.pdf?VersionId=N4f0Tid4j60OtRPUnJdof8yJT4Jq5pa_",
            "attendance": [
                "Villegas",
                "Mosley",
                "La Spata",
                "Hall",
                "Chico",
                "Lee",
                "Lopez",
                "Cruz",
                "Cardona",
                "Waguespack",
                "Manaa-Hoppenworth",
                "Gutierrez",
                "Tabares",
                "Mitchell",
                "Napolitano",
                "Reilly",
            ],
        },
        "2023-06-13": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/ECTD%20Rule%2045%20Report%20June%202023%20%281%29.pdf?VersionId=4jgh83QF6H3mvrTCOAXndKI69_QiYy3E",
            "attendance": [
                "Villegas",
                "Mosley",
                "La Spata",
                "Mitchell",
                "Chico",
                "Lee",
                "Gutierrez",
                "Lopez",
                "Cruz",
                "Cardona",
                "Napolitano",
                "Manaa-Hoppenworth",
                "Hall",
            ],
        },
    },
    "Committee on Immigrant and Refugee Rights": {
        "2023-09-29": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/Immigrant%20and%20Refugee%20Committee%20-%20Rule%2045%20-%2009-23.pdf?VersionId=5et93XhJ4gami7pB4VcSLczWarMsd4Ei",
            "attendance": [
                "Vasquez",
                "Taylor",
                "Dowell",
                "Fuentes",
                "Taliaferro",
                "Cruz",
                "Cardona",
                "Ramirez-Rosa",
                "Manaa-Hoppenworth",
                "Rodriguez",
                "Rodriguez Sanchez",
                "Hadden",
                "Gutierrez",
            ],
        },
        "2023-07-26": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/Immigrant%20and%20Refugee%20Committee%20-%20Rule%2045%20-%2007-23%20%281%29.pdf?VersionId=PrS4UgYgSTcxkQM8mPjTVWZuWcSsifPI",
            "attendance": [
                "Vasquez",
                "Taylor",
                "Dowell",
                "Gutierrez",
                "Rodriguez",
                "Fuentes",
                "Taliaferro",
                "Cruz",
                "Cardona",
                "Rodriguez Sanchez",
                "Ramirez-Rosa",
                "Knudsen",
                "Manaa-Hoppenworth",
                "Hadden",
            ],
        },
        "2023-06-28": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/Immigrant%20and%20Refugee%20Committee%20-%20Rule%2045%20-%2006-23.pdf?VersionId=GL.iygmYcZFtgJGRnX5WBT4XhyQM78Wg",
            "attendance": [
                "Vasquez",
                "Taylor",
                "Dowell",
                "Gutierrez",
                "Rodriguez",
                "Fuentes",
                "Taliaferro",
                "Cruz",
                "Cardona",
                "Ramirez-Rosa",
                "Knudsen",
                "Manaa-Hoppenworth",
                "Hadden",
            ],
        },
    },
    "Committee on Health and Human Relations": {
        "2023-09-26": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/HHR%20Rule%2045%20Report%209_26_23.pdf?VersionId=RCc3V6IYpLKCG.PhkFTlrA_e3Vu_07ez",
            "attendance": [
                "Rodriguez Sanchez",
                "Ramirez",
                "Yancy",
                "Hadden",
                "Fuentes",
                "Cruz",
                "Lawson",
                "Manaa-Hoppenworth",
                "Robinson",
                "Ramirez-Rosa",
                "Gutierrez",
            ],
        },
        "2023-07-24": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/HHR%20Rule%2045%20-%207-23.pdf?VersionId=mdftjVy85e7StrSxph17ptOKjfLidsah",
            "attendance": [
                "Rodriguez Sanchez",
                "Ramirez",
                "Robinson",
                "Yancy",
                "Gutierrez",
                "Lopez",
                "Coleman",
                "Hadden",
                "Sigcho-Lopez",
                "Fuentes",
                "Cruz",
                "Ramirez-Rosa",
                "Lawson",
                "Manaa-Hoppenworth",
            ],
        },
    },
    "Committee on Budget and Government Operations": {
        "2023-09-12": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/CBGO.MonthlyRule45ReportSeptember2023.pdf?VersionId=bO41bahoM98QSt6DCAwbiogEJCsUGrUH",
            "attendance": [
                "Ervin",
                "Lee",
                "La Spata",
                "Dowell",
                "Robinson",
                "Mitchell",
                "Harris",
                "Ramirez",
                "Quinn",
                "Lopez",
                "Moore, David H.",
                "Mosley",
                "Rodriguez",
                "Scott, Monique L.",
                "Sigcho-Lopez",
                "Burnett",
                "Taliaferro",
                "Cardona",
                "Rodriguez Sanchez",
                "Conway",
                "Ramirez-Rosa",
                "Villegas",
                "Mitts",
                "Sposato",
                "Nugent",
                "Vasquez",
                "Napolitano",
                "Knudsen",
                "Martin",
                "Hadden",
                "Silverstein",
                "O'Shea",
            ],
        },
        "2023-07-18": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/CBGO.MonthlyRule45ReportJuly2023.pdf?VersionId=A1JSjpADqpZHmW6rO_u2WAEUuQ69EBBl",
            "attendance": [
                "Ervin",
                "Lee",
                "La Spata",
                "Dowell",
                "Yancy",
                "Mitchell",
                "Harris",
                "Ramirez",
                "Quinn",
                "Lopez",
                "Moore, David H.",
                "O'Shea",
                "Rodriguez",
                "Scott, Monique L.",
                "Sigcho-Lopez",
                "Burnett",
                "Taliaferro",
                "Cardona",
                "Rodriguez Sanchez",
                "Conway",
                "Ramirez-Rosa",
                "Villegas",
                "Sposato",
                "Nugent",
                "Vasquez",
                "Napolitano",
                "Knudsen",
                "Martin",
                "Hadden",
                "Silverstein",
            ],
        },
        "2023-06-20": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/CBGOMonthlyRule45ReportJune2023.pdf?VersionId=n1F2DWeKkAMgmyZ761_9PIu_6h9lDgmt",
            "attendance": [
                "Ervin",
                "Lee",
                "La Spata",
                "Dowell",
                "Robinson",
                "Yancy",
                "Mitchell",
                "Harris",
                "Ramirez",
                "Moore, David H.",
                "O'Shea",
                "Mosley",
                "Rodriguez",
                "Burnett",
                "Rodriguez Sanchez",
                "Conway",
                "Ramirez-Rosa",
                "Villegas",
                "Mitts",
                "Nugent",
                "Knudsen",
                "Martin",
                "Hadden",
            ],
        },
        "2023-05-30": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/Budget%20Committee%20Rule%2045%20-%2005-23_0.pdf?VersionId=dWs67sB1RhNt_c7zXxrk.KrxROYufi33",
            "attendance": [
                "Ervin",
                "Lee",
                "La Spata",
                "Dowell",
                "Robinson",
                "Yancy",
                "Ramirez",
                "Lopez",
                "Moore, David H.",
                "O'Shea",
                "Mosley",
                "Rodriguez",
                "Scott, Monique L.",
                "Burnett",
                "Taliaferro",
                "Cardona",
                "Conway",
                "Ramirez-Rosa",
                "Villegas",
                "Mitts",
                "Sposato",
                "Nugent",
                "Vasquez",
                "Napolitano",
                "Knudsen",
                "Martin",
                "Silverstein",
            ],
        },
    },
    "Committee on Workforce Development": {
        "2023-09-07": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/September%207th%20Workforce%20Development%20Rule%2045%20Report.pdf?VersionId=8xZYV4d9lgjm4hW7YoVYM0x3oKPpahza",
            "attendance": [
                "Rodriguez",
                "Gutierrez",
                "Yancy",
                "Hall",
                "Ramirez",
                "Quinn",
                "Taliaferro",
                "Vasquez",
                "Clay",
            ],
        },
        "2023-06-12": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/Cmte%20on%20Workforce%20Dev%20June%20Rule%2045.pdf?VersionId=e06ydcdniIgGNi.YhFmBLa7Y0wIw1esa",
            "attendance": [
                "Rodriguez",
                "Gutierrez",
                "Yancy",
                "Hall",
                "Beale",
                "Chico",
                "Ramirez",
                "Quinn",
                "Coleman",
                "Curtis",
                "Taliaferro",
                "Ramirez-Rosa",
                "Sposato",
                "Vasquez",
                "Clay",
            ],
        },
    },
    "Committee on Public Safety": {
        "2023-10-13": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/Public%20Safety%20Committee%20Rule%2045%20-%2010-23%20v2.pdf?VersionId=WXwAqfrTYLK_gK5fy0dKmKVWwgnHUIlu",
            "attendance": [
                "Hall",
                "Lee",
                "Tabares",
                "Ervin",
                "Cardona",
                "Sposato",
                "Nugent",
                "Gardiner",
                "Clay",
                "Taliaferro",
            ],
        },
        "2023-07-11": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/Public_Safety_Committee_Rule_45-07-23_2.pdf?VersionId=mbUyRHMPDI_37rFFXE0WjMqR8mcz9aE.",
            "committee": "Committee on Public Safety",
            "meeting_date": "2023-07-11",
            "attendance": [
                "Hopkins",
                "Yancy",
                "Chico",
                "Gutierrez",
                "Lopez",
                "Curtis",
                "Tabares",
                "Sigcho-Lopez",
                "Fuentes",
                "Taliaferro",
                "Sposato",
                "Vasquez",
                "Knudsen",
                "Gardiner",
                "Manaa-Hoppenworth",
                "Hadden",
                "Silverstein",
            ],
        },
    },
    "Committee on License and Consumer Protection": {
        "2023-07-13": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/July_License_Committee_Rule_450723.pdf?VersionId=AMYT5w69U2rlo3IAAVvqmRihLNxanOts",
            "committee": "Committee on License and Consumer Protection",
            "meeting_date": "2023-07-13",
            "attendance": [
                "Silverstein",
                "Chico",
                "Moore, David H.",
                "O'Shea",
                "Scott, Monique L.",
                "Cardona",
                "Conway",
                "Mitts",
                "Sposato",
                "Napolitano",
                "Lawson",
                "Clay",
                "Martin",
                "Lopez",
                "Coleman",
            ],
        },
        "2023-06-15": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/June_License_Committee_Rule_450623.pdf?VersionId=GfzEynZPEfnp6BCqnivVISzjMbY85LLC",
            "attendance": [
                "Silverstein",
                "Chico",
                "Moore, David H.",
                "Cardona",
                "Waguespack",
                "Conway",
                "Villegas",
                "Sposato",
                "Napolitano",
                "Reilly",
                "Gardiner",
                "Clay",
                "Martin",
                "Quinn",
                "Scott, Monique L.",
                "Lawson",
            ],
        },
        "2023-05-30": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/License%20Committee%20Rule%2045%20-%2005-23.pdf?VersionId=m5fqTHoA1ntdPwNeK3rodmu9Cd_ilxg4",
            "attendance": [
                "Silverstein",
                "Chico",
                "Coleman",
                "Moore, David H.",
                "Scott, Monique L.",
                "Cardona",
                "Waguespack",
                "Conway",
                "Villegas",
                "Sposato",
                "Napolitano",
                "Reilly",
                "Lawson",
                "Gardiner",
                "Martin",
                "Burnett",
                "Cruz",
            ],
        },
    },
    "Committee on Housing and Real Estate": {
        "2023-10-10": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/HRE%20RULE%2045%2010OCT23.pdf?VersionId=zEy4hYH.vqFDVWrwWcR2h9K3OhgULrtg",
            "attendance": [
                "Sigcho-Lopez",
                "Mitchell",
                "La Spata",
                "Harris",
                "Robinson",
                "Taylor",
                "Tabares",
                "Villegas",
                "Clay",
                "Manaa-Hoppenworth",
                "Scott, Monique L.",
                "Fuentes",
                "Ramirez-Rosa",
                "Burnett",
                "Rodriguez Sanchez",
                "Quinn",
                "Moore, David H.",
            ],
        },
        "2023-08-28": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/HRE%20RULE45%2028AUG23.pdf?VersionId=OanykQe4Z2OhHbQqYRxDK_T325Cts24x",
            "attendance": [
                "Sigcho-Lopez",
                "Mitchell",
                "La Spata",
                "Dowell",
                "Quinn",
                "Moore, David H.",
                "Taylor",
                "Tabares",
                "Scott, Monique L.",
                "Fuentes",
                "Burnett",
                "Ramirez-Rosa",
                "Villegas",
                "Manaa-Hoppenworth",
                "Hadden",
            ],
        },
        "2023-07-27": {
            "source": None,
            "attendance": [
                "Sigcho-Lopez",
                "Mitchell",
                "La Spata",
                "Dowell",
                "Robinson",
                "Harris",
                "Quinn",
                "Moore, David H.",
                "Taylor",
                "Tabares",
                "Scott, Monique L.",
                "Fuentes",
                "Burnett",
                "Rodriguez Sanchez",
                "Ramirez-Rosa",
                "Villegas",
                "Clay",
                "Manaa-Hoppenworth",
                "Hadden",
            ],
        },
        "2023-07-10": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/RULE45JULY2023.pdf?VersionId=LbwYOtSKb9dnOjf3EmqRhPvxcntNWVWA",
            "attendance": [
                "Sigcho-Lopez",
                "Mitchell",
                "La Spata",
                "Dowell",
                "Robinson",
                "Harris",
                "Quinn",
                "Taylor",
                "Tabares",
                "Scott, Monique L.",
                "Fuentes",
                "Burnett",
                "Ramirez-Rosa",
                "Villegas",
                "Clay",
                "Manaa-Hoppenworth",
                "Hadden",
            ],
        },
        "2023-06-12": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/RULE45JUNE2023.pdf?VersionId=1WEvyrbZOSPhZkLejexsNZc4ppGOwWcg",
            "attendance": [
                "Sigcho-Lopez",
                "Mitchell",
                "La Spata",
                "Dowell",
                "Robinson",
                "Harris",
                "Quinn",
                "Moore, David H.",
                "Taylor",
                "Tabares",
                "Scott, Monique L.",
                "Fuentes",
                "Burnett",
                "Ramirez-Rosa",
                "Villegas",
                "Clay",
                "Manaa-Hoppenworth",
            ],
        },
    },
    "Committee on Ethics and Government Oversight": {
        "2023-07-13": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/July%202023%20Rule%2045%20Report%20Ethics%20Committee.pdf?VersionId=0.D_2QKie5F.1QRceaEOqaEqZ1P8Ng0M",
            "attendance": [
                "Martin",
                "Hadden",
                "Lee",
                "O'Shea",
                "Taylor",
                "Tabares",
                "Scott",
                "Taliaferro",
                "Waguespack",
                "Sposato",
                "Nugent",
                "Vasquez",
                "Lawson",
            ],
        }
    },
    "Committee on Zoning, Landmarks and Building Standards": {
        "2023-09-12": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/Zoning%20Committee%20Rule%2045%20Report%20-%2009-22.pdf?VersionId=vKjSF.5ZJAdN_iz_uz8QEcDw.89ZJ4wh",
            "committee": "Committee on Zoning, Landmarks and Building Standards",
            "attendance": [
                "Ramirez-Rosa",
                "Lawson",
                "La Spata",
                "Hopkins",
                "Dowell",
                "Hall",
                "Harris",
                "Beale",
                "Ramirez",
                "Moore, David H.",
                "Mosley",
                "Sigcho-Lopez",
                "Fuentes",
                "Cruz",
                "Conway",
                "Villegas",
                "Knudsen",
                "Clay",
            ],
        },
        "2023-06-20": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/Zoning_Committee_Rule_45_Report_0623.pdf?VersionId=mhELh5KTzkf_zfhTWc0Fnz6S789xI.2I",
            "attendance": [
                "Ramirez-Rosa",
                "Lawson",
                "La Spata",
                "Hopkins",
                "Dowell",
                "Hall",
                "Harris",
                "Beale",
                "Ramirez",
                "Moore, David H.",
                "Mosley",
                "Sigcho-Lopez",
                "Fuentes",
                "Burnett",
                "Cruz",
                "Conway",
                "Villegas",
                "Reilly",
                "Knudsen",
                "Clay",
                "Hopkins",
            ],
        },
        "2023-07-18": {
            "source": "https://chicityclerk.s3.us-west-2.amazonaws.com/s3fs-public/reports/Zoning%20Committee%20Rule%2045%20Report%20-%2007-23%20%281%29.pdf?VersionId=usw23oMreZkSMUdpTY_WJ52l8R9Oq1xQ",
            "attendance": [
                "Ramirez-Rosa",
                "Lawson",
                "La Spata",
                "Dowell",
                "Hall",
                "Harris",
                "Ramirez",
                "Moore, David H.",
                "Sigcho-Lopez",
                "Fuentes",
                "Burnett",
                "Cruz",
                "Conway",
                "Villegas",
                "Knudsen",
                "Clay",
            ],
        },
    },
}
