MEMBER_DISTRICTS = {
    "Alan Hertzberg": 2,
    "Anthony Coghill": 4,
    "Barbara Burns": 1,
    "Bob O'Connor": 5,
    "Bobby Wilson": 1,
    "Bruce A. Kraus": 3,
    "Corey O'Connor": 5,
    "Dan Cohen": 8,
    "Dan Deasy": 2,
    "Dan Gilman": 8,
    "Darlene M. Harris": 1,
    "Deborah L. Gross": 7,
    "Douglas Shields": 5,
    "Erika Strassburger": 8,
    "Gene Ricciardi": 3,
    "Jeffrey S. Koch": 3,
    "Jim Ferlo": 7,
    "Jim Motznik": 4,
    "Len Bodack": 7,
    "Luke Ravensthal": 1,
    "Michael Diven": 4,
    "Natalia Rudiak": 4,
    "Patrick Dowd": 7,
    "R. Daniel Lavelle": 6,
    "Reverend Ricky V. Burgess": 9,
    "Sala Udin": 6,
    "Theresa Kail-Smith": 2,
    "Thomas Sciulli": 5,
    "Tonya D. Payne": 6,
    "Twanda Carlisle": 9,
    "Valerie McDonald-Roberts": 9,
    "William Peduto": 8
}